# Generated by Django 6.1 on 2026-09-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0001_initial'),
        ('myapp', '0003_userprofile_budget_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilityprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_profile', to='myapp.userprofile'),
        ),
    ]
