# Generated by Django 6.1 on 2026-09-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(db_index=True, max_length=200)),
                ('field', models.CharField(max_length=100)),
                ('value', models.BooleanField(blank=True, null=True)),
                ('source', models.CharField(choices=[('photo_verification', 'Photo Verification'), ('business_declaration', 'Business Declaration'), ('osm', 'OpenStreetMap'), ('provider_data', 'Provider Structured Data'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('business_declared', 'Business Declared'), ('osm_supported', 'OSM Supported'), ('ai_supported', 'AI Supported'), ('unknown', 'Unknown'), ('conflicting', 'Conflicting')], default='unknown', max_length=50)),
                ('confidence', models.IntegerField(default=50, help_text='0-100 evidence confidence score')),
                ('evidence_reference', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessibilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, default='default_traveler', max_length=120, unique=True)),
                ('wheelchair_required', models.BooleanField(default=False, help_text='Wheelchair boarding and transit required')),
                ('step_free_required', models.BooleanField(default=False, help_text='Step-free routes and ramps required')),
                ('accessible_vehicle_required', models.BooleanField(default=False, help_text='Accessible low-floor / ramp vehicle required')),
                ('accessible_venue_required', models.BooleanField(default=False, help_text='Accessible entrance and venue required')),
                ('accessible_toilet_preferred', models.BooleanField(default=False, help_text='Accessible restroom preferred')),
                ('elevator_preferred', models.BooleanField(default=False, help_text='Elevator / lift preferred over stairs')),
                ('reduced_walking', models.BooleanField(default=False, help_text='Minimize walking distance between transfers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessibilityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accessibility_photos/%Y/%m/')),
                ('model_used', models.CharField(default='gemini-2.0-flash', max_length=100)),
                ('detected', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('evidence', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
