import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import './styles.css';

const places = [
  {name:'Munnar', type:'Tea country', img:'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=900&q=80', rating:'4.9', tag:'Low-impact stay'},
  {name:'Coorg', type:'Forest trails', img:'https://images.unsplash.com/photo-1580974852861-c381510bc98f?auto=format&fit=crop&w=900&q=80', rating:'4.8', tag:'Accessible'},
  {name:'Hampi', type:'Living heritage', img:'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=900&q=80', rating:'4.7', tag:'Verified clean'}
];

function Logo(){ return <Link className="logo" to="/"><span>◉</span> eco<span>trail</span></Link> }
function Navbar(){return <header className="nav"><Logo/><nav><a href="#how">How it works</a><Link to="/discover">Explore</Link><a href="#impact">Our impact</a></nav><div className="nav-actions"><Link className="text-link" to="/login">Log in</Link><Link className="btn small" to="/signup">Start planning <b>↗</b></Link></div></header>}
function Footer(){return <footer><Logo/><p>Better journeys leave lighter footprints.</p><div><a href="#">Privacy</a><a href="#">Help centre</a><a href="#">Instagram</a></div></footer>}
function Pill({children}){return <span className="pill">{children}</span>}

function Landing(){return <><Navbar/><main className="landing">
 <section className="hero"><div className="hero-copy"><Pill>✦ Travel thoughtfully, beautifully</Pill><h1>Go places.<br/><i>Leave less behind.</i></h1><p>Plan trips that feel good in every sense — lighter on the planet, easier to navigate, and made around you.</p><div className="hero-buttons"><Link className="btn" to="/planner">Plan your eco-trip <b>↗</b></Link><a className="play" href="#how">▶ <span>See how Eco-Twin works</span></a></div><div className="hero-proof"><b>4.9/5</b><span className="avatars">◉ ◉ ◉ ◉</span><span>Loved by 40,000+ mindful travellers</span></div></div>
 <div className="hero-art"><div className="sun"></div><div className="mountain m1"></div><div className="mountain m2"></div><div className="mountain m3"></div><div className="cloud c1"></div><div className="cloud c2"></div><div className="route">⌁</div><div className="float-card card-a">🌿 <b>42% less CO₂</b><small>Your journey, made lighter</small></div><div className="float-card card-b">✦ <b>Comfort, checked</b><small>Access & hygiene verified</small></div></div></section>
 <section className="intro" id="impact"><div><Pill>THE ECOTRAIL DIFFERENCE</Pill><h2>The trip you want.<br/><em>The impact you choose.</em></h2></div><p>EcoTrail creates an <b>Eco-Twin</b> for every journey: a more considered alternative that makes the trade-offs clear, so you stay in control.</p></section>
 <section className="twin" id="how"><div className="twin-image"><div className="twin-overlay"><span>YOUR EC0-TWIN</span><b>75 kg CO₂ saved</b></div></div><div className="twin-copy"><Pill>MEET YOUR ECO-TWIN</Pill><h2>A better version of every escape.</h2><p>See your regular plan beside a smarter alternative. Compare carbon, cost, time, comfort and accessibility — at a glance.</p><div className="metrics"><div><strong>−42%</strong><span>carbon emissions</span></div><div><strong>₹1,840</strong><span>average saved</span></div><div><strong>✓</strong><span>needs considered</span></div></div><Link className="arrow-link" to="/comparison">Compare a sample trip →</Link></div></section>
 <section className="benefits"><article><span>♧</span><h3>Kind to the planet</h3><p>Lower-impact routes and stays, always explained.</p></article><article><span>◌</span><h3>Built around you</h3><p>Accessibility, budget and comfort are not afterthoughts.</p></article><article><span>✦</span><h3>Trust in every detail</h3><p>AI-verified accessibility and hygiene insights.</p></article></section>
 <section className="cta"><Pill>READY WHEN YOU ARE</Pill><h2>Travel with more<br/>intention.</h2><Link className="btn light" to="/planner">Start planning <b>↗</b></Link></section>
 </main><Footer/></>}

function Auth({signup=false}){const nav=useNavigate(); return <main className="auth"><div className="auth-visual"><Logo/><div><Pill>WELCOME TO ECOTRAIL</Pill><h1>Every better<br/>journey starts<br/><i>with a choice.</i></h1><p>Find travel that works for you and the world around you.</p></div><small>● 40,000+ intentional travellers</small></div><section className="auth-form"><Link className="back" to="/">← Back to home</Link><div className="form-box"><Logo/><h2>{signup?'Create your account':'Welcome back'}</h2><p>{signup?'Start planning journeys that matter.':'Your next thoughtful journey is waiting.'}</p>{signup&&<label>Full name<input placeholder="Your name"/></label>}<label>Email address<input type="email" placeholder="you@example.com"/></label><label>Password<input type="password" placeholder="••••••••"/></label>{!signup&&<a className="forgot" href="#">Forgot password?</a>}<button className="btn full" onClick={()=>nav('/dashboard')}>{signup?'Create account':'Log in'} <b>→</b></button><div className="or">or continue with</div><div className="social"><button>G Google</button><button>● Apple</button></div><p className="switch">{signup?'Already have an account?':'New to EcoTrail?'} <Link to={signup?'/login':'/signup'}>{signup?'Log in':'Create an account'}</Link></p></div></section></main>}

const Side=()=> <aside className="sidebar"><Logo/><div className="side-links"><NavLink to="/dashboard">▦ Overview</NavLink><NavLink to="/planner">⌁ Plan a trip</NavLink><NavLink to="/discover">⌕ Discover</NavLink><NavLink to="/saved">♡ Saved places</NavLink></div><div className="side-bottom"><NavLink to="/profile">◎ Profile & settings</NavLink><a href="#">↪ Log out</a></div></aside>;
function AppLayout({children}){return <div className="app-shell"><Side/><main className="app-main"><header className="app-head"><div className="search">⌕ Search journeys, places...</div><div>⌁ <span className="profile-dot">A</span></div></header>{children}</main></div>}
function Dashboard(){return <AppLayout><section className="dash-hero"><div><Pill>THURSDAY, 11 SEPTEMBER</Pill><h1>Good morning, Aditya <i>✦</i></h1><p>Where will your next better journey take you?</p><Link className="btn" to="/planner">Plan a trip <b>↗</b></Link></div><div className="dash-art">✈<span>Mumbai</span><span>Goa</span></div></section><section className="dash-grid"><div className="section-title"><div><Pill>YOUR TRIPS</Pill><h2>Keep exploring</h2></div><Link to="/saved">View all →</Link></div><div className="trip-row"><TripCard/><div className="mini-card"><b>♧ 1,280 kg</b><span>CO₂ avoided together</span><small>That’s like growing 21 trees.</small></div><div className="mini-card"><b>★ 12 places</b><span>Saved for later</span><small>Your travel wishlist is growing.</small></div></div></section><section><div className="section-title"><div><Pill>FOR YOUR NEXT ESCAPE</Pill><h2>Made for you</h2></div><Link to="/discover">Discover more →</Link></div><div className="place-grid">{places.map(p=><Place key={p.name} p={p}/>)}</div></section></AppLayout>}
function TripCard(){return <div className="trip-card"><div className="trip-photo"></div><div><Pill>UPCOMING · 24–28 SEP</Pill><h3>Coastal slow days in Goa</h3><p>2 travellers · Mumbai → Goa</p><div className="trip-stats"><span>♧ 46% lower CO₂</span><span>✓ All stays verified</span></div></div><b>→</b></div>}
function Place({p}){return <Link to="/discover" className="place"><img src={p.img}/><div><Pill>{p.tag}</Pill><h3>{p.name}</h3><p>{p.type} <span>★ {p.rating}</span></p></div></Link>}
function Planner(){const nav=useNavigate(); return <AppLayout><section className="page-top"><Pill>PLAN A JOURNEY</Pill><h1>Let's make this trip count.</h1><p>Tell us what matters to you. We’ll shape an Eco-Twin around it.</p></section><section className="planner"><div className="planner-form"><label>Where are you going?<div className="input-icon">⌖ <input placeholder="Search a destination" defaultValue="Goa, India"/></div></label><div className="two"><label>Leaving from<input defaultValue="Mumbai, India"/></label><label>Travel dates<input defaultValue="24 Sep — 28 Sep"/></label></div><label>Who’s going?<input defaultValue="2 travellers"/></label><h3>What matters most?</h3><div className="choices"><button className="selected">♧ Lower impact</button><button>♿ Accessibility</button><button>₹ Budget-friendly</button><button>☼ More comfort</button></div><button className="btn full" onClick={()=>nav('/results')}>Find my Eco-Twin <b>→</b></button></div><aside className="planning-note"><span>✦</span><h3>Travel your way.</h3><p>Your preferences help us find options that feel right — not just look good on paper.</p><ul><li>✓ Transport comparisons</li><li>✓ Verified stays</li><li>✓ Weather-aware ideas</li></ul></aside></section></AppLayout>}
function Results(){return <AppLayout><section className="page-top compact"><Pill>MUMBAI → GOA · 24–28 SEP</Pill><h1>Your journey, <i>considered.</i></h1><p>We found options that balance your priorities beautifully.</p></section><div className="results-tabs"><button className="active">Recommended</button><button>Fastest</button><button>Lowest cost</button><button>Lowest impact</button></div><section className="results"><div><Result type="eco"/><Result type="regular"/></div><aside className="result-aside"><Pill>YOUR IMPACT</Pill><h3>Choose the Eco-Twin</h3><div className="big-number">−46%<span>less CO₂</span></div><p>Choosing train over flight saves the equivalent of 14 kg of coal burned.</p><Link className="arrow-link" to="/comparison">See full comparison →</Link></aside></section></AppLayout>}
function Result({type}){let eco=type==='eco'; return <article className={'result '+type}><div className="result-img"></div><div className="result-content"><Pill>{eco?'ECOTRAIL PICK':'REGULAR OPTION'}</Pill><h2>{eco?'Konkan Railway':'Direct flight'}</h2><p>{eco?'Mumbai CSMT → Madgaon · Overnight':'Mumbai → Goa · 1h 20m'}</p><div className="result-details"><span>◷ {eco?'10h 45m':'3h 40m'}</span><span>₹ {eco?'1,280':'5,180'}</span><span>♧ {eco?'35':'130'} kg CO₂</span></div>{eco&&<div className="verified">✓ Accessibility & hygiene details verified</div>}</div><button>⌄</button></article>}
function Comparison(){return <AppLayout><section className="page-top compact"><Pill>YOUR ECO-TWIN</Pill><h1>Same destination.<br/><i>Better way to get there.</i></h1></section><section className="compare"><div className="compare-head"><div>✈ <b>Regular trip</b><span>Direct flight</span></div><div className="eco-head">♧ <b>Eco-Twin</b><span>Konkan Railway</span></div></div>{[['Carbon emissions','130 kg CO₂','35 kg CO₂','73% lower'],['Total cost','₹5,180','₹1,280','₹3,900 saved'],['Travel time','3h 40m','10h 45m','+7h 05m'],['Comfort','Standard seat','Sleeper cabin','More room'],['Accessibility','Limited info','Verified access','Checked for you']].map(x=><div className="compare-row" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><b className="green">{x[2]} <small>{x[3]}</small></b></div>)}</section><div className="compare-cta"><span>♧</span><div><b>Your Eco-Twin saves 95 kg of CO₂</b><p>That's the clearest route to a lighter journey.</p></div><Link className="btn" to="/saved">Save this trip <b>→</b></Link></div></AppLayout>}
function Discover(){return <AppLayout><section className="discover-title"><Pill>EXPLORE MINDFULLY</Pill><h1>Places that give back.</h1><p>Find inspiring destinations with lighter footprints and richer experiences.</p><div className="discover-search">⌕ <input placeholder="Where do you want to go?"/><button>Search</button></div></section><div className="filters"><button className="active">For you</button><button>Nature</button><button>Culture</button><button>Beach</button><button>Weekend escape</button><button>♿ Accessible</button></div><div className="place-grid large">{places.concat(places).map((p,i)=><Place key={i} p={{...p,name:i>2?['Alleppey','Spiti','Pondicherry'][i-3]:p.name}}/>)}</div></AppLayout>}
function Saved(){return <AppLayout><section className="page-top compact"><Pill>YOUR COLLECTION</Pill><h1>Saved for <i>some day.</i></h1><p>All the little possibilities waiting for the right moment.</p></section><div className="saved-tabs"><button className="active">Trips (2)</button><button>Places (12)</button></div><div className="saved-list"><TripCard/><TripCard/></div></AppLayout>}
function Profile(){return <AppLayout><section className="page-top compact"><Pill>YOUR ACCOUNT</Pill><h1>Profile & preferences</h1><p>Keep your travel experience personal, practical and thoughtful.</p></section><section className="profile-page"><div className="profile-card"><div className="avatar">A</div><div><h2>Aditya Kadam</h2><p>aditya@example.com</p></div><button>Edit profile</button></div><div className="settings"><div><h3>Travel preferences</h3><p>Low impact · Comfort · Train travel</p></div><button>Manage →</button><div><h3>Accessibility needs</h3><p>No preferences added yet</p></div><button>Manage →</button><div><h3>Notifications</h3><p>Trip updates and tailored ideas</p></div><button>Manage →</button></div></section></AppLayout>}
function App(){return <Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Auth/>}/><Route path="/signup" element={<Auth signup/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/planner" element={<Planner/>}/><Route path="/results" element={<Results/>}/><Route path="/comparison" element={<Comparison/>}/><Route path="/discover" element={<Discover/>}/><Route path="/saved" element={<Saved/>}/><Route path="/profile" element={<Profile/>}/></Routes>};
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
