# Generated by Django 6.1 on 2026-09-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_userprofile_budget_preference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('duration_days', models.IntegerField(default=1)),
                ('travel_dates', models.CharField(blank=True, default='', max_length=100)),
                ('transport_mode', models.CharField(blank=True, default='', max_length=100)),
                ('total_cost', models.IntegerField(default=0)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('eco_score', models.IntegerField(default=0)),
                ('carbon_emissions', models.FloatField(default=0.0, help_text='Total journey carbon emissions in kg CO2e')),
                ('carbon_saved', models.CharField(blank=True, default='', max_length=100)),
                ('accessibility_rating', models.FloatField(default=0.0)),
                ('accessibility_verified', models.BooleanField(default=False)),
                ('status', models.CharField(default='Saved', max_length=50)),
                ('cover_image', models.URLField(blank=True, default='', max_length=1024)),
                ('stays', models.CharField(blank=True, default='Verified Eco Homestay', max_length=255)),
                ('itinerary_data', models.JSONField(blank=True, default=dict)),
                ('recommendation_data', models.JSONField(blank=True, default=dict)),
                ('eco_twin_data', models.JSONField(blank=True, default=dict)),
                ('show_your_math_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_trips', to='myapp.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
